### PR TITLE
Fix login error, await for promises

### LINKED ISSUE #521: Fix the error that makes it impossible to login
Cherry-picked to this commit: https://github.com/CodeForPoznan/pah-fm/commit/cb49a583b59b03b7c2e20578944deef4238b2519
Probably something with missing await. Can be observed on https://dev.pahfm.codeforpoznan.pl

### PR DESCRIPTION
**Pull request by arturtamborski**
Fixes #521

### CODE REVIEW

File: frontend/src/store/modules/http/state.js [hunk 1]
```diff
@@ -1,8 +1,7 @@
 export const TOKEN = 'TOKEN';
 
 export default {
-  // LEGACY SUPPORT
-  // After merge to new version remove localStorage
-  [TOKEN]: localStorage.getItem('jwt') || null,
+    // LEGACY SUPPORT
```
Comment (magul) [inline frontend/src/store/modules/http/state.js:4]: that's just nitpicking, but in JavaScript world, indentation is usually multiplication of 2.

Comment (arturtamborski) [reply frontend/src/store/modules/http/state.js:4]: Yeah, I know, I actually removed that code but then reverted it with wrong indentation, hence the change. Will fix it
